/**
 * gate-report.ts — the ONE door between the sealed gate's report and an agent
 * that is about to try to fix it.
 *
 * READ `dashboard/STATUS.md` §0 ("The held-out boundary") BEFORE ADDING A FIELD
 * HERE. This file is not a formatter. It is the reason `heldOutPass` still means
 * something after the GATE/FIX loop exists.
 *
 * WHAT GOES WRONG WITHOUT IT. A `ContainerResult` carries
 * `criterionCoverage[].testRefs` — documented in the scorer protocol as "Test
 * titles that asserted it". Phases 0, 0.1 and 0.2 sealed `results/scorer-out/`
 * precisely because that file names the held-out suite. Hand the raw report to a
 * fixing agent and the agent learns the held-out tests by name; it can then
 * write code shaped to those titles, `heldOutPass` becomes a measurement of
 * nothing, and NOTHING IN THE SYSTEM DETECTS THAT. The verdict still looks like
 * a verdict.
 *
 *   VISIBLE to a fixing agent                 HELD OUT from a fixing agent
 *   ─────────────────────────────────         ─────────────────────────────────
 *   tier0 gate failures, allowlisted          criterionCoverage[].testRefs
 *     build / typecheck / lint / boot           (test TITLES — never)
 *     routes / stub markers / exploits        criterionCoverage[].detail
 *     data / screenshots                      suiteExecution.reportProblem
 *   exploitFindings (blocking)                GATE:suite-green's own detail
 *   domFindings                               held-out suite: COUNT + TIER only
 *   per-tier unmet COUNTS                       "2 FUNCTIONAL criteria unmet"
 *
 * THE PLAN FOR THIS PHASE SAID "tier0 failures survive in full — they are
 * objective, not test-derived". THAT IS TRUE OF EVERY GATE EXCEPT ONE, and the
 * exception is the one that matters. `GATE:suite-green`'s detail is assembled in
 * `bakeoff/src/scorer-container.ts` from the held-out runner's own output tail
 * (up to 4,000 characters of it), the `titlePath` of each excused failure, and
 * the paths of uncollected frozen files. That is the held-out suite, quoted
 * verbatim. So detail crosses by ALLOWLIST, not by denylist: a gate id nobody
 * here has reasoned about gets its failure reported and its detail withheld. A
 * new gate added upstream therefore fails closed, which is the direction that
 * does not silently reopen the boundary.
 */

import { GATE_IDS } from "bakeoff/dist/scorer-protocol.js";
import type { ContainerResult, Tier0GateResult } from "bakeoff/dist/scorer-protocol.js";
import type { CriterionTier } from "bakeoff/dist/contracts.js";
import { truncate } from "./claude-common.js";

export type FailureClass =
  | "install"
  | "build"
  | "boot"
  | "route"
  | "visual"
  | "test-infra"
  | "logic"
  | "structure";

/**
 * Every class, in the order a fixer should attack them.
 *
 * Ordering lives with the union rather than in the triage module because it is a
 * property of the classes themselves: fixing a visual nit while the build is
 * broken wastes a round, whatever routes it.
 */
export const ALL_FAILURE_CLASSES: readonly FailureClass[] = Object.freeze([
  "install",
  "build",
  "boot",
  "route",
  "test-infra",
  "logic",
  "structure",
  "visual",
]);

export interface FixableFailure {
  readonly id: string;
  readonly klass: FailureClass;
  /** Safe to put in a prompt. Built from source literals, never from output. */
  readonly summary: string;
  /** Redacted tier0/finding detail. NEVER a held-out test title. */
  readonly detail: string;
  readonly command: string | null;
  readonly exitCode: number | null;
}

export interface AgentVisibleReport {
  readonly failures: readonly FixableFailure[];
  /** Held-out suite: counts by tier ONLY. Never titles, never assertions. */
  readonly heldOutUnmet: Readonly<Record<CriterionTier, number>>;
  readonly infraFailure: string | null;
}

/** What a withheld detail says. It says something, so it cannot read as "no detail". */
export const WITHHELD_DETAIL =
  "detail withheld: this gate's detail is derived from the held-out suite (test titles, runner output). " +
  "The held-out half is not visible to a fixing agent — fix against visible-acceptance/ and the tier-0 gates.";

const ZERO_UNMET: Readonly<Record<CriterionTier, number>> = Object.freeze({
  BLOCKING: 0,
  FUNCTIONAL: 0,
  QUALITY: 0,
});

/**
 * Gate ids whose `detail` and `command` may cross to an agent.
 *
 * Every one of these is generated by running the ARTEFACT's own toolchain
 * against the artefact: a compiler error, a lint report, an HTTP status, a
 * missing screenshot. None of them reads the frozen suite. Absent from this
 * list, and deliberately: `GATE:suite-green` (quotes the held-out runner),
 * `GATE:suite-intact` (names frozen suite files) and
 * `GATE:no-protected-path-writes` (names the frozen file a copy matched).
 */
const DETAIL_ALLOWLIST: ReadonlySet<string> = new Set([
  GATE_IDS.build,
  GATE_IDS.typecheck,
  GATE_IDS.lint,
  GATE_IDS.boot,
  GATE_IDS.routes,
  GATE_IDS.noStubMarkers,
  GATE_IDS.noRewardHackExploits,
  GATE_IDS.dataPresent,
  GATE_IDS.screenshotsPresent,
]);

/** Longest detail that reaches a prompt. A fixer needs the error, not the log. */
const MAX_DETAIL = 1_200;

/**
 * Dependency-resolution markers in a build gate's detail.
 *
 * WHY A TEXT MATCH IS ACCEPTABLE HERE AND NOWHERE ELSE IN THIS FILE. The
 * container folds install into build on purpose — "a failed install is a failed
 * build" (`bakeoff/src/scorer-container.ts`) — so there is no `GATE:install` to
 * key on. Without this the `install` class has no producer, and
 * `dependency-manager` is a route that can never fire: a branch that looks like
 * policy and is dead. The cost of a wrong match is routing a compiler error to
 * the dependency specialist for one round; the cost of no match is a permanently
 * dead specialist. Nothing about the boundary depends on this.
 */
const INSTALL_MARKERS =
  /\bERESOLVE\b|\bETARGET\b|\bENOTFOUND\b|npm error code E|peer dep|unable to resolve dependency|could not resolve dependency|lockfile|pip install|poetry install|yarn install|npm (ci|install)\b/i;

interface ClassifiableGate {
  readonly id: string;
  readonly detail?: string;
}

/** The bare id: `GATE:build` and `build` are the same gate. */
function bareId(id: string): string {
  return id.startsWith("GATE:") ? id.slice("GATE:".length) : id;
}

/**
 * Which specialist's problem this is.
 *
 * TOTAL BY CONSTRUCTION. An id nobody has reasoned about classifies `logic` and
 * is routed to the debugger — never dropped. A dropped failure is a failure the
 * loop believes it fixed.
 */
export function classify(gate: ClassifiableGate): FailureClass {
  const id = bareId(gate.id);
  switch (id) {
    case "build":
      return INSTALL_MARKERS.test(gate.detail ?? "") ? "install" : "build";
    case "typecheck":
      return "build";
    case "lint":
      return "structure";
    case "boot":
      return "boot";
    case "routes":
      return "route";
    case "screenshots-present":
    case "screenshots":
      return "visual";
    case "no-reward-hack-exploits":
      // The exploits live in test paths and config — `test-automator` owns that
      // ground. A reward-hack marker is not a logic bug, it is a rigged harness.
      return "test-infra";
    case "no-stub-markers":
    case "data-present":
    case "suite-green":
    default:
      return "logic";
  }
}

/** DOM findings that are about how it looks rather than what it does. */
const VISUAL_DOM_KINDS: ReadonlySet<string> = new Set([
  "image_natural_width_zero",
  "horizontal_overflow",
  "default_serif_font",
  "placeholder_text",
]);

function tier0Failure(gate: Tier0GateResult): FixableFailure {
  const allowed = DETAIL_ALLOWLIST.has(gate.id);
  return {
    id: gate.id,
    klass: classify({ id: gate.id, detail: allowed ? gate.detail : "" }),
    // `name` is a source literal in scorer-container.ts, unlike `detail`, which
    // is assembled at run time from whatever the gate observed.
    summary: gate.name.length > 0 ? gate.name : gate.id,
    detail: allowed ? truncate(gate.detail, MAX_DETAIL) : WITHHELD_DETAIL,
    command: allowed ? gate.command : null,
    exitCode: allowed ? gate.exitCode : null,
  };
}

/**
 * The report a fixing agent is allowed to read.
 *
 * `null` in means the gate produced no machine-readable result, which is an
 * INFRA failure and not an empty pass — "the gate could not run" and "the gate
 * passed" must never look alike, and an empty `failures` list is exactly this
 * loop's green condition.
 */
export function toAgentVisible(container: ContainerResult | null): AgentVisibleReport {
  if (container === null) {
    return {
      failures: [],
      heldOutUnmet: ZERO_UNMET,
      infraFailure: "the sealed container produced no machine-readable result",
    };
  }

  if (container.infrastructureErrors.length > 0) {
    // No fix work at all. The artefact may be perfect; a browser would not
    // launch. Proposing fixes here burns quota on a problem that is not there —
    // and the criterion counts are meaningless because the suite never ran, so
    // they are reported as zero rather than as a wall of "unmet".
    return {
      failures: [],
      heldOutUnmet: ZERO_UNMET,
      infraFailure: container.infrastructureErrors.map((e) => truncate(e, 400)).join("; "),
    };
  }

  const failures: FixableFailure[] = [];
  for (const gate of container.tier0) {
    if (gate.outcome !== "fail") continue;
    failures.push(tier0Failure(gate));
  }

  for (const finding of container.exploitFindings) {
    // Non-blocking findings gate nothing (scorer-protocol: "it is reported so a
    // reviewer can see it, and it gates nothing"). A bounded loop fixes what
    // stands between the run and green; chasing the rest spends a round.
    if (!finding.blocking) continue;
    failures.push({
      id: `exploit:${finding.kind}`,
      klass: "test-infra",
      summary: `reward-hack exploit ${finding.kind} in ${finding.path}`,
      detail: truncate(
        `${finding.rule}${finding.line === null ? "" : ` at line ${String(finding.line)}`}: ${finding.detail}`,
        MAX_DETAIL,
      ),
      command: null,
      exitCode: null,
    });
  }

  for (const finding of container.domFindings) {
    failures.push({
      id: `dom:${finding.kind}`,
      klass: VISUAL_DOM_KINDS.has(finding.kind) ? "visual" : "logic",
      summary: `${finding.kind} on flow ${finding.flowId} at ${finding.breakpoint}`,
      detail: truncate(finding.detail, MAX_DETAIL),
      command: null,
      exitCode: null,
    });
  }

  return {
    failures,
    heldOutUnmet: countUnmet(container),
    infraFailure: null,
  };
}

/**
 * Per-tier counts of criteria the held-out suite did not satisfy.
 *
 * THE ONLY THING TAKEN FROM `criterionCoverage`. Not the ids, not the titles,
 * not the details — a count and a tier. That is enough for a fixer to know there
 * is work left and not enough to know what the work asserts.
 *
 * `unasserted` counts as unmet, per the scorer protocol's own note: "THIS IS A
 * FAILURE, NOT A SKIP. Absence of evidence is not evidence of satisfaction."
 */
function countUnmet(container: ContainerResult): Readonly<Record<CriterionTier, number>> {
  const counts: Record<CriterionTier, number> = { BLOCKING: 0, FUNCTIONAL: 0, QUALITY: 0 };
  for (const coverage of container.criterionCoverage) {
    if (coverage.outcome === "passed") continue;
    counts[coverage.tier] += 1;
  }
  return Object.freeze(counts);
}

/** Total unmet across every tier. For REPORTING — never for a stop condition. */
export function unmetTotal(report: AgentVisibleReport): number {
  return report.heldOutUnmet.BLOCKING + report.heldOutUnmet.FUNCTIONAL + report.heldOutUnmet.QUALITY;
}

/**
 * Unmet criteria that can actually change the verdict.
 *
 * BLOCKING + FUNCTIONAL, because that is precisely what `computeHeldOutPass`
 * reads (`bakeoff/src/contracts.ts`): `criteriaResults.filter((c) => c.tier ===
 * "BLOCKING" || c.tier === "FUNCTIONAL")`. QUALITY is "REPORTED, NEVER GATING"
 * — the scorer went out of its way to fix exactly that after the 4B run, where a
 * BLOCKING gate carrying QUALITY failures silently overrode the decision and
 * made `pass_with_notes` unreachable.
 *
 * A LOOP THAT COUNTED QUALITY HERE WOULD GATE ON IT. Measured on the way in:
 * with QUALITY in the stop condition, a build that passed every tier-0 gate and
 * left one QUALITY criterion unmet spent a fix round and two extra container
 * runs — out of the owner's shared rate-limit window — and then finished
 * `passed` anyway, because `heldOutPass` was true the whole time.
 */
export function gatingUnmet(report: AgentVisibleReport): number {
  return report.heldOutUnmet.BLOCKING + report.heldOutUnmet.FUNCTIONAL;
}

/**
 * Nothing left that this loop can usefully do: no gate failed and no GATING
 * criterion is unmet.
 *
 * A QUALITY shortfall does not hold the loop open — and is not hidden either. It
 * is stated in every fix prompt and in the backlog, where it is reported rather
 * than gating, which is what the tier means.
 */
export function isGreen(report: AgentVisibleReport): boolean {
  return report.infraFailure === null && report.failures.length === 0 && gatingUnmet(report) === 0;
}
